### ISSUE TITLE
No module named 'albumentations'

### ISSUE THREAD

**Issue by hellboywyh** [Lam1360/YOLOv3-model-pruning#3]
When I run the test.py code, the error occurs:
```bash
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from utils.datasets import *
  File "YOLOv3-model-pruning/utils/datasets.py", line 10, in <module>
    from utils.augmentations import augment
  File "YOLOv3-model-pruning/utils/augmentations.py", line 4, in <module>
    import albumentations as A
ModuleNotFoundError: No module named 'albumentations'
```

**Comment by smartcai** [comment]
@hellboywyh pip install albumentations

**Comment by Lam1360** [comment]
@hellboywyh, pip install albumentations, albumentations is a libray for image augmentation

**Comment by sureshkm-ai** [comment]
I am facing the same error in my jupyter notebook though I am able to execute it from terminal.

**Comment by dibyacharya** [comment]
> I am facing the same error in my jupyter notebook though I am able to execute it from terminal.

check on annaconda commadpromt

**Comment by Sakib1263** [comment]
Just upgrade other dependencies and libraries such as OpenCV to their latest versions and use Python 3.9. It worked for me after I did this.

**Comment by talhaanwarch** [comment]
> I am facing the same error in my jupyter notebook though I am able to execute it from terminal.

upgrading jupyter notebook resolved the issue for me

**Comment by shubhamias12** [comment]
NO able to resolve the issue can anyone help ?

**Comment by shubhamias12** [comment]
Traceback (most recent call last):
  File "e:\Dissertation\coding\run\ResUNetPlusPlus-with-CRF-and-TTA-master\ResUNetPlusPlus-with-CRF-and-TTA-master\infer_image_all.py", line 11, in <module>
    from albumentations import (
  File "C:\Users\sharm\AppData\Local\Programs\Python\Python39\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .core.composition import *
  File "C:\Users\sharm\AppData\Local\Programs\Python\Python39\lib\site-packages\albumentations\core\composition.py", line 8, in <module>
    from albumentations.augmentations.keypoints_utils import KeypointsProcessor
ModuleNotFoundError: No module named 'albumentations.augmentations'
