### ISSUE TITLE
执行test_prune.py进行剪枝，报错

### ISSUE THREAD

**Issue by baidu88vip** [Lam1360/YOLOv3-model-pruning#39]
报错内容

=====

Detecting objects: 100% 42/42 [01:02<00:00,  1.14s/it]
Computing AP: 100% 3/3 [00:00<00:00, 303.82it/s]
Threshold should be less than 0.3998.
The corresponding prune ratio is 0.769.
Channels with Gamma value less than 0.4403 are pruned!
Detecting objects: 100% 42/42 [01:01<00:00,  1.11s/it]
Traceback (most recent call last):
  File "test_prune.py", line 78, in <module>
    threshold = prune_and_eval(model, sorted_bn, percent)
  File "test_prune.py", line 69, in prune_and_eval
    mAP = eval_model(model_copy)[2].mean()
  File "test_prune.py", line 27, in <lambda>
    nms_thres=0.5, img_size=model.img_size, batch_size=24)
  File "/YOLOv3-model-pruning/test.py", line 55, in evaluate
    assert sample_metrics != []
AssertionError

=======
自己数据集classes=3，请指教

**Comment by yyx1107** [comment]
我也遇到这个错误，test_prune.py中 percent差不多最多设成0.35，再大就会报错，不知道怎么能达到作者设置的0.85呀 @Lam1360

**Comment by realtainyi** [comment]
I had the same problem.

**Comment by yyx1107** [comment]
> I had the same problem.

应该是稀疏化少了，多弄几个epoch试试，我只弄了四十

**Comment by xdl932365660** [comment]
我也遇到这个错误

**Comment by habarbecue** [comment]
我的只能设置为0.25

**Comment by habarbecue** [comment]
这样精度为0

**Comment by habarbecue** [comment]
> 我也遇到这个错误，test_prune.py中％差不多最多设成0.35，再大就会报错，不知道怎么能达到作者设置的0.85呀@Lam1360

我的只能设置为0.25，可以加个邮箱交流下吗

**Comment by shenguquanxin** [comment]
同样遇到这个问题

**Comment by habarbecue** [comment]
你的训练精度达到多少？


------------------ 原始邮件 ------------------
发件人: "shenguquanxin"<notifications@github.com>;
发送时间: 2019年8月22日(星期四) 下午2:50
收件人: "Lam1360/YOLOv3-model-pruning"<YOLOv3-model-pruning@noreply.github.com>;
抄送: "Anitsirhc"<734590632@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Lam1360/YOLOv3-model-pruning] 执行test_prune.py进行剪枝，报错 (#39)




同样遇到这个问题

**Comment by shenguquanxin** [comment]
> 你的训练精度达到多少？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "shenguquanxin"<notifications@github.com>; 发送时间: 2019年8月22日(星期四) 下午2:50 收件人: "Lam1360/YOLOv3-model-pruning"<YOLOv3-model-pruning@noreply.github.com>; 抄送: "Anitsirhc"<734590632@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Lam1360/YOLOv3-model-pruning] 执行test_prune.py进行剪枝，报错 (#39) 同样遇到这个问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.



> 你的训练精度达到多少？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "shenguquanxin"<notifications@github.com>; 发送时间: 2019年8月22日(星期四) 下午2:50 收件人: "Lam1360/YOLOv3-model-pruning"<YOLOv3-model-pruning@noreply.github.com>; 抄送: "Anitsirhc"<734590632@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Lam1360/YOLOv3-model-pruning] 执行test_prune.py进行剪枝，报错 (#39) 同样遇到这个问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

percent=0.25：map=0
percent=0.85 ：assert sample_metrics != []       AssertionError

**Comment by yyx1107** [comment]
> > 我也遇到这个错误，test_prune.py中％差不多最多设成0.35，再大就会报错，不知道怎么能达到作者设置的0.85呀@Lam1360
> 
> 我的只能设置为0.25，可以加个邮箱交流下吗

完全按照作者的设置进行稀疏化，就可以设成0.85啦

**Comment by shenguquanxin** [comment]
> > > 我也遇到这个错误，test_prune.py中％差不多最多设成0.35，再大就会报错，不知道怎么能达到作者设置的0.85呀@Lam1360
> > 
> > 
> > 我的只能设置为0.25，可以加个邮箱交流下吗
> 
> 完全按照作者的设置进行稀疏化，就可以设成0.85啦

就是说：baseline和稀疏化训练的epochs都取默认值100吗，这样就可以啦？多谢~我去做一下

**Comment by yyx1107** [comment]
可以先直接稀疏训练~


 
---原始邮件---
发件人: "shenguquanxin"<notifications@github.com>
发送时间: 2019年8月22日(星期四) 下午4:58
收件人: "Lam1360/YOLOv3-model-pruning"<YOLOv3-model-pruning@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"yyx1107"<1017176539@qq.com>;
主题: Re: [Lam1360/YOLOv3-model-pruning] 执行test_prune.py进行剪枝，报错 (#39)


   
我也遇到这个错误，test_prune.py中％差不多最多设成0.35，再大就会报错，不知道怎么能达到作者设置的0.85呀@Lam1360
  
我的只能设置为0.25，可以加个邮箱交流下吗
  
完全按照作者的设置进行稀疏化，就可以设成0.85啦
  
就是说：baseline和稀疏化训练的epochs都取默认值100吗，这样就可以啦？多谢~我去做一下

**Comment by habarbecue** [comment]
> > > > 我也遇到这个错误，test_prune.py中％差不多最多设成0.35，再大就会报错，不知道怎么能达到作者设置的0.85呀@Lam1360
> > > 
> > > 
> > > 我的只能设置为0.25，可以加个邮箱交流下吗
> > 
> > 
> > 完全按照作者的设置进行稀疏化，就可以设成0.85啦
> 
> 就是说：baseline和稀疏化训练的epochs都取默认值100吗，这样就可以啦？多谢~我去做一下

需要迭代式sr吗

**Comment by shenguquanxin** [comment]
> > > > > 我也遇到这个错误，test_prune.py中％差不多最多设成0.35，再大就会报错，不知道怎么能达到作者设置的0.85呀@Lam1360
> > > > 
> > > > 
> > > > 我的只能设置为0.25，可以加个邮箱交流下吗
> > > 
> > > 
> > > 完全按照作者的设置进行稀疏化，就可以设成0.85啦
> > 
> > 
> > 就是说：baseline和稀疏化训练的epochs都取默认值100吗，这样就可以啦？多谢~我去做一下
> 
> 需要迭代式sr吗

我完全照作者命令来的，不会报错，但是最后mAP=0.65左右

**Comment by broliao** [comment]
@shenguquanxin 我完全按作者的命令来（直接进行稀疏化训练），生成了21个.pth，我试了几个，把persent设置为0.85还是会报错，请问你是怎么操作的呢？
![image](https://user-images.githubusercontent.com/49137103/64394263-e4d77a80-d087-11e9-899f-15394f1f24a3.png)

**Comment by shenguquanxin** [comment]
> @shenguquanxin 我完全按作者的命令来（直接进行稀疏化训练），生成了21个.pth，我试了几个，把persent设置为0.85还是会报错，请问你是怎么操作的呢？
> ![image](https://user-images.githubusercontent.com/49137103/64394263-e4d77a80-d087-11e9-899f-15394f1f24a3.png)

我也是一样的。已经放弃这个git了

**Comment by yyx1107** [comment]
稀疏化了几个epoch，太少的话剪不了那么多，所以会报错


 
---原始邮件---
发件人: "broliao"<notifications@github.com&gt;
发送时间: 2019年9月6日(星期五) 上午9:23
收件人: "Lam1360/YOLOv3-model-pruning"<YOLOv3-model-pruning@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"yyx1107"<1017176539@qq.com&gt;;
主题: Re: [Lam1360/YOLOv3-model-pruning] 执行test_prune.py进行剪枝，报错 (#39)



@shenguquanxin 我完全按作者的命令来（直接进行稀疏化训练），生成了21个.pth，我试了几个，把persent设置为0.85还是会报错，请问你是怎么操作的呢？

**Comment by broliao** [comment]
@yyx1107 我稀疏化训练了100个epoch，让他自动停止训练为止！

**Comment by yyx1107** [comment]
我开始也是不行，稀疏到80也只能剪0.2,0.3，可能因为我改了些什么，后来我重新下载了一下，什么都不改，直接按照作者稀疏化，就不会出那个什么assert error了。


 
---原始邮件---
发件人: "broliao"<notifications@github.com&gt;
发送时间: 2019年9月6日(星期五) 上午9:55
收件人: "Lam1360/YOLOv3-model-pruning"<YOLOv3-model-pruning@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"yyx1107"<1017176539@qq.com&gt;;
主题: Re: [Lam1360/YOLOv3-model-pruning] 执行test_prune.py进行剪枝，报错 (#39)



@yyx1107 我稀疏化训练了100个epoch，让他自动停止训练为止！

**Comment by broliao** [comment]
@yyx1107 你是重新下载作者的项目，然后再百分之百的按作者的方法进行训练？还是说是基于你修改之后的代码，然后按作者的方法训练？

**Comment by yyx1107** [comment]
什么都不改，直接稀疏化训练了一百次，就可以了，因为我之前改过些东西，可能是这个原因。


 
---原始邮件---
发件人: "broliao"<notifications@github.com&gt;
发送时间: 2019年9月6日(星期五) 上午10:35
收件人: "Lam1360/YOLOv3-model-pruning"<YOLOv3-model-pruning@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"yyx1107"<1017176539@qq.com&gt;;
主题: Re: [Lam1360/YOLOv3-model-pruning] 执行test_prune.py进行剪枝，报错 (#39)



@yyx1107 你是重新下载作者的项目，然后再百分之百的按作者的方法进行训练？还是说是基于你修改之后的代码，然后按作者的方法训练？

**Comment by broliao** [comment]
那有可能

**Comment by hellojava-ts-hdu** [comment]
> > 你的训练精度达到多少？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "shenguquanxin"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年8月22日(星期四) 下午2:50 收件人: "Lam1360/YOLOv3-model-pruning"[YOLOv3-model-pruning@noreply.github.com](mailto:YOLOv3-model-pruning@noreply.github.com); 抄送: "Anitsirhc"[734590632@qq.com](mailto:734590632@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [Lam1360/YOLOv3-model-pruning] 执行test_prune.py进行剪枝，报错 (#39) 同样遇到这个问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> > 你的训练精度达到多少？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "shenguquanxin"[notifications@github.com](mailto:notifications@github.com); 发送时间: 2019年8月22日(星期四) 下午2:50 收件人: "Lam1360/YOLOv3-model-pruning"[YOLOv3-model-pruning@noreply.github.com](mailto:YOLOv3-model-pruning@noreply.github.com); 抄送: "Anitsirhc"[734590632@qq.com](mailto:734590632@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [Lam1360/YOLOv3-model-pruning] 执行test_prune.py进行剪枝，报错 (#39) 同样遇到这个问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> percent=0.25：map=0
> percent=0.85 ：assert sample_metrics != [] AssertionError

请问你解决了么

**Comment by hellojava-ts-hdu** [comment]
为什么我的剪枝percent=0.25，map就等于0了，大佬求解答

**Comment by xiayanqian** [comment]
把batch_size调小一点
