### ISSUE TITLE
求助：进行稀疏化训练报错

### ISSUE THREAD

**Issue by wd923923** [Lam1360/YOLOv3-model-pruning#43]
(pytorch-yolov3) C:\YOLOv3-model-pruning-master>python train.py --model_def config/yolov3-hand.cfg
Namespace(batch_size=16, checkpoint_interval=5, data_config='config/oxfordhand.data', debug_file='debug', epochs=100, evaluation_interval=1, img_size=416, lr=0.001, model_def='config/yolov3-hand.cfg', multiscale_training=False, n_cpu=4, pretrained_weights='weights/yolov3.weights', s=0.01, sr=False)
Traceback (most recent call last):
  File "C:\Users\923\Anaconda3\envs\pytorch-yolov3\lib\site-packages\tensorboardX\record_writer.py", line 40, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: 'logs\\0821-01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 50, in <module>
    logger = Logger("logs")
  File "C:\YOLOv3-model-pruning-master\utils\logger.py", line 27, in __init__
    self.writer = SummaryWriter(os.path.join(log_dir, timestamp))
  File "C:\Users\923\Anaconda3\envs\pytorch-yolov3\lib\site-packages\tensorboardX\writer.py", line 257, in __init__
    self._get_file_writer()
  File "C:\Users\923\Anaconda3\envs\pytorch-yolov3\lib\site-packages\tensorboardX\writer.py", line 321, in _get_file_writer
    **self.kwargs)
  File "C:\Users\923\Anaconda3\envs\pytorch-yolov3\lib\site-packages\tensorboardX\writer.py", line 93, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "C:\Users\923\Anaconda3\envs\pytorch-yolov3\lib\site-packages\tensorboardX\event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "C:\Users\923\Anaconda3\envs\pytorch-yolov3\lib\site-packages\tensorboardX\record_writer.py", line 44, in directory_check
    os.makedirs(path)
  File "C:\Users\923\Anaconda3\envs\pytorch-yolov3\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] 目录名称无效。: 'logs\\0821-01:30'

**Comment by chensi41** [comment]
目录名称无效。: 'logs\0821-01:30' 把"-"改成"_"试试

**Comment by zxealous** [comment]
请问您的问题解决了吗 我也遇到了一样的问题，是因为windows的原因吗？

**Comment by chensi41** [comment]
utils/logger.py 26行改一下就可以了 比如
"timestamp = datetime.fromtimestamp(time.time()).strftime('%m%d_%H_%M')"

**Comment by zxealous** [comment]
好的我试试






------------------ 原始邮件 ------------------
发件人: chensi41 <notifications@github.com>
发送时间: 2019年8月22日 12:07
收件人: Lam1360/YOLOv3-model-pruning <YOLOv3-model-pruning@noreply.github.com>
抄送: zxealous <1498678317@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[Lam1360/YOLOv3-model-pruning] 求助：进行稀疏化训练报错 (#43)




utils/logger.py 26行改一下就可以了 比如
 "timestamp = datetime.fromtimestamp(time.time()).strftime('%m%d_%H_%M')"

**Comment by zxealous** [comment]
> utils/logger.py 26行改一下就可以了 比如
> "timestamp = datetime.fromtimestamp(time.time()).strftime('%m%d_%H_%M')"

已经弄好了 谢谢
