### ISSUE TITLE
求助 训练自己数据集出现问题 是我标签的原因吗

### ISSUE THREAD

**Issue by zxealous** [Lam1360/YOLOv3-model-pruning#46]
RuntimeError: cuda runtime error (59) : device-side assert triggered at C:/w/1/s/tmp_conda_3.6_041836/conda/conda-bld/pytorch_1556684464974/work/aten/src\THC/THCTensorMathCompareT.cuh:69

上面是报错内容，我的标签格式如下：
0 0.54921875 0.3546875 0.009375000000000001 0.026041666666666668
0 0.66796875 0.4109375 0.009375000000000001 0.026041666666666668

**Comment by zxealous** [comment]
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    loss, outputs = model(imgs, targets)
  File "D:\ProgramFiles\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\zcy\YOLOv3-model-pruning\models.py", line 267, in forward
    x, layer_loss = module[0](x, targets, img_dim)  # module是nn.Sequential()，所以要取[0]
  File "D:\ProgramFiles\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\zcy\YOLOv3-model-pruning\models.py", line 190, in forward
    ignore_thres=self.ignore_thres,
  File "D:\zcy\YOLOv3-model-pruning\utils\utils.py", line 320, in build_targets
    iou_scores[b, best_n, gj, gi] = bbox_iou(pred_boxes[b, best_n, gj, gi], target_boxes, x1y1x2y2=False)
RuntimeError: CUDA error: device-side assert triggered

抱歉 上面复制错了这个才是错误

**Comment by yyx1107** [comment]
只有一类吗

**Comment by zxealous** [comment]
> 只有一类吗

一共有5类的

**Comment by duanyuqi987** [comment]
我的也一样？怎么处理的？
